### ISSUE TITLE
syntax error in autogen.sh

### ISSUE THREAD

**Issue by Duhjoker** [gregkh/usbutils#123]
hi 

  getting a syntax error when using autogen.sh for configure but cant figure out how to fix 

./configure: line 4500: syntax error near unexpected token `LIBUSB,'
./configure: line 4500: `PKG_CHECK_MODULES(LIBUSB, libusb-1.0 >= 1.0.9)'

**Comment by gregkh** [comment]
Do you have libusb installed properly?

What distro is this?  What version of libusb?

**Comment by Duhjoker** [comment]
Yes I'm using a proot of Ubuntu 20.04. I have used the instruction here https://zoomadmin.com/HowToInstall/UbuntuPackage/libusb-1.0-0

**Comment by gregkh** [comment]
You probably also need the libusb-dev package if you are going to build something against it.

Why not just use the usbutils version that comes with the distro?

**Comment by tormodvolden** [comment]
If only libusb-dev was missing there would be a proper error message from configure, and not a syntax error. This is probably due to missing installation of pkg-config (which includes pkg.m4). Anyway it also looks like a stale tree: libusb 1.0.9 was the requirement only up to version 0.10, back in 2018. FYI Ubuntu 20.04 ships with version 012.

**Comment by gregkh** [comment]
Ok, not having `pkg-config installed isn't a usbutils issue, now closing, thanks!
